name: Build Enmity (Bleeding Edge)
on:
  push:
    branches:
      - bleeding-edge
  workflow_dispatch:

jobs:
  build:
    name: Build Enmity (Bleeding Edge)
    runs-on: macos-latest
    steps:   
      - uses: actions/checkout@v3
        with:
          ref: 'bleeding-edge'
          submodules: true
          
      - name: Prepare Procursus
        uses: localdevice/procursus-action@main
        with:
          packages: ldid make
          cache-path: ${{ github.workspace }}/procursus

      - name: Prepare Theos
        uses: localdevice/theos-action@main
        with:
          cache-dir-theos: ${{ github.workspace }}/theos
          cache-dir-sdks: ${{ github.workspace }}/theos/sdks
          
      - name: Prepare Azule
        uses: actions/checkout@v3
        with:
          repository: Al4ise/Azule
          path: Azule

      - name: Prepare Enmity Patcher
        run : |
          curl -L https://github.com/enmity-mod/patcher/releases/latest/download/patcher.mac-amd64 -o ${{ github.workspace }}/patcher
          chmod +x patcher

      - name: Patch Discord
        run : |
          ${{ github.workspace }}/patcher

      - name: Build Package
        id: find_deb
        run : |
          gmake clean package FINALPACKAGE=1 BETA=1
          echo "::set-output name=deb::$(find packages -name "*.deb" -print -quit)"

      - name: Create IPA
        run : |
          mkdir out
          ${{ github.workspace }}/Azule/azule -p "Enmity Alpha" -i Enmity.ipa -o out -f ${{ steps.find_deb.outputs.deb }}
          mv $(find out -name "*.ipa" -print -quit) out/Enmity-Alpha.ipa

      - name: Set Outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.vars.outputs.sha_short }} ALPHA
          files:  |
            ${{ steps.find_deb.outputs.deb }}
            out/Enmity-Alpha.ipa
          prerelease: true
