name: Build Enmity (Manual)

on:
  workflow_dispatch:
    inputs:
      enmity_version:
        description: "Enmity's Version"
        default: ""
        required: true
        type: string
      enmity_changes:
        description: "Enmity's Changelog"
        default: ""
        required: false
        type: string
      discord_version:
        description: "Discord's Version"
        default: ""
        required: true
        type: string
      discord_changes:
        description: "Discord's Changelog"
        default: ""
        required: false
        type: string
      decrypted_discord:
        description: "Direct URL to a DECRYPTED Discord IPA"
        default: ""
        required: true
        type: string
      patch_discord:
        description: "Patch Discord"
        default: true
        required: false
        type: boolean
      enable_react_dev_tools:
        description: "Enable React Dev Tools"
        default: false
        required: false
        type: boolean
      create_release:
        description: "Create a Draft Release"
        default: false
        required: false
        type: boolean

jobs:
  build:
    name: Build Enmity
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Prepare Procursus
        uses: localdevice/procursus-action@main
        with:
          packages: ldid make
          cache-path: ${{ github.workspace }}/procursus

      - name: Prepare Theos
        uses: localdevice/theos-action@main
        with:
          cache-dir-theos: ${{ github.workspace }}/theos
          cache-dir-sdks: ${{ github.workspace }}/theos/sdks

      - name: Prepare Azule
        uses: actions/checkout@v3
        with:
          repository: Al4ise/Azule
          path: Azule
          
      - name: Prepare Enmity Patcher
        run : |
          curl -L https://github.com/enmity-mod/patcher/releases/latest/download/patcher.mac-amd64 -o ${{ github.workspace }}/patcher
          chmod +x patcher
          
      - name: Patch Discord
        if: ${{ inputs.patch_discord }}
        run : |
          curl -L ${{ inputs.decrypted_discord }} -o ${{ github.workspace }}/Discord.ipa
          ${{ github.workspace }}/patcher -d ${{ github.workspace }}/Discord.ipa
          mkdir out
          
      - name: Build Package
        run: |
          rm -f packages/*
          gmake clean package FINALPACKAGE=1
          mv $(find packages -name "*.deb" -print -quit) out/enmity.beta.deb
          
      - name: Create IPA
        run : |
          ${{ github.workspace }}/Azule/azule -p "Enmity Beta" -i Enmity.ipa -o out -f out/enmity.beta.deb
          mv out/Enmity+enmity.beta.deb.ipa out/enmity.beta.ipa
          
      - name: Set Outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build Dev Package
        if: ${{ inputs.enable_react_dev_tools }}
        run: |
          rm -f packages/*
          echo $"$(sed 's/Name\:.*/Name\: Enmity (Dev)/' control)" > control
          echo $"$(sed 's/Package\:.*/Package\: app.enmity.dev/' control)" > control
          gmake clean package FINALPACKAGE=1 DEVTOOLS=1
          mv $(find packages -name "*.deb" -print -quit) out/enmity.dev.deb

      - name: Create Dev IPA
        if: ${{ inputs.enable_react_dev_tools }}
        run : |
          ${{ github.workspace }}/Azule/azule -i Enmity.ipa -o out -f out/enmity.dev.deb
          mv out/Enmity+enmity.dev.deb.ipa out/enmity.dev.ipa

      - name: Create Release
        if: ${{ inputs.create_release }}
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          ENMITY_VERSION: ${{ inputs.enmity_version }}
          ENMITY_CHANGES: ${{ inputs.enmity_changes }}
          DISCORD_VERSION: ${{ inputs.discord_version }}
          DISCORD_CHANGES: ${{ inputs.discord_changes }}
        with:
          tag_name: beta-${{ steps.vars.outputs.sha_short }}
          name: beta-${{ steps.vars.outputs.sha_short }} Discord Version - ${{ env.DISCORD_VERSION }} & Enmity Version - ${{ env.ENMITY_VERSION }}
          body: ${{ env.DISCORD_CHANGES }} ${{ env.ENMITY_CHANGES }}
          files:  |
            out/*
          draft: true
          prerelease: true
