name: Build Enmity (Manual)

on:
  workflow_dispatch:
    inputs:
      enmity_version:
        description: "Enmity's Version"
        default: ""
        required: true
        type: string
      enmity_changes:
        description: "Enmity's Changelog"
        default: ""
        required: false
        type: string
      discord_version:
        description: "Discord's Version"
        default: ""
        required: true
        type: string
      discord_changes:
        description: "Discord's Changelog"
        default: ""
        required: false
        type: string
      decrypted_discord:
        description: "Direct URL to a DECRYPTED Discord IPA"
        default: ""
        required: true
        type: string
      patch_discord:
        description: "Patch Discord"
        default: true
        required: false
        type: boolean
      create_release:
        description: "Create a Draft Release"
        default: false
        required: false
        type: boolean

jobs:
  build:
    name: Build Enmity
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Prepare Procursus
        uses: localdevice/procursus-action@main
        with:
          packages: ldid make
          cache-path: ${{ github.workspace }}/procursus

      - name: Prepare Theos
        uses: localdevice/theos-action@main
        with:
          cache-dir-theos: ${{ github.workspace }}/theos
          cache-dir-sdks: ${{ github.workspace }}/theos/sdks

      - name: Prepare Azule
        uses: actions/checkout@v3
        with:
          repository: Al4ise/Azule
          path: Azule
          
      - name: Prepare Enmity Patcher
        run : |
          curl -L https://github.com/enmity-mod/patcher/releases/latest/download/patcher.mac-amd64 -o ${{ github.workspace }}/patcher
          chmod +x patcher
          
      - name: Patch Discord
        if: ${{ inputs.patch_discord }}
        run : |
          curl -L ${{ inputs.decrypted_discord }} -o ${{ github.workspace }}/Discord.ipa
          ${{ github.workspace }}/patcher -d ${{ github.workspace }}/Discord.ipa
          
      - name: Build Package
        id: find_deb
        run : |
          gmake clean package FINALPACKAGE=1 BETA=1
          echo "::set-output name=deb::$(find packages -name "*.deb" -print -quit)"
          
      - name: Create IPA
        run : |
          mkdir out
          ${{ github.workspace }}/Azule/azule -p "Enmity Beta" -i Enmity.ipa -o out -f ${{ steps.find_deb.outputs.deb }}
          mv $(find out -name "*.ipa" -print -quit) out/Enmity-Beta.ipa
          
      - name: Set Outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Create Release
        if: ${{ inputs.create_release }}
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          ENMITY_VERSION: ${{ inputs.enmity_version }}
          ENMITY_CHANGES: ${{ inputs.enmity_changes }}
          DISCORD_VERSION: ${{ inputs.discord_version }}
          DISCORD_CHANGES: ${{ inputs.discord_changes }}
        with:
          tag_name: beta-${{ steps.vars.outputs.sha_short }}
          name: beta-${{ steps.vars.outputs.sha_short }} Discord Version - ${{ env.DISCORD_VERSION }} & Enmity Version - ${{ env.ENMITY_VERSION }}
          body: ${{ env.DISCORD_CHANGES }} ${{ env.ENMITY_CHANGES }}
          files:  |
            ${{ steps.find_deb.outputs.deb }}
            out/Enmity-Beta.ipa
          draft: true
          prerelease: true
