name: Build Enmity (Stable)
on:
  push:
    tags:
       - '*'
  pull_request:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    name: Build Enmity (Stable)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
          submodules: true
          
      - name: Prepare Procursus
        uses: localdevice/procursus-action@main
        with:
          packages: ldid make
          cache-path: ${{ github.workspace }}/procursus

      - name: Prepare Theos
        uses: localdevice/theos-action@main
        with:
          cache-dir-theos: ${{ github.workspace }}/theos
          cache-dir-sdks: ${{ github.workspace }}/theos/sdks

      - name: Prepare Azule
        uses: actions/checkout@v3
        with:
          repository: Al4ise/Azule
          path: Azule

      - name: Prepare Enmity Patcher
        run : |
          curl -L https://github.com/enmity-mod/patcher/releases/latest/download/patcher.mac-amd64 -o ${{ github.workspace }}/patcher
          chmod +x patcher

      - name: Patch Discord
        run : |
          ${{ github.workspace }}/patcher

      - name: Build Package
        id: find_deb
        run : |
          gmake clean package FINALPACKAGE=1
          echo "::set-output name=deb::$(find packages -name "*.deb" -print -quit)"

      - name: Create IPA
        run : |
          mkdir out
          ${{ github.workspace }}/Azule/azule -i Enmity.ipa -o out -f ${{ steps.find_deb.outputs.deb }}
          mv $(find out -name "*.ipa" -print -quit) out/Enmity.ipa

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release-${{ github.ref_name }}
          files:  |
            ${{ steps.find_deb.outputs.deb }}
            out/Enmity.ipa
